config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to "/restaurants/#{@restaurant[:id]}"
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to "/restaurants/#{@review.restaurant[:id]}"
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants index</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>Name: <%=restaurant.name%> (<%= link_to 'details', restaurant_path(restaurant) %>)</li>
  <% end %>
</ul>

<p><%= link_to 'Add a new restaurant', new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
  <div class='container'>
    <div class='card'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='card'>
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class='card'>
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div class='card'>
      <%= f.label :category %>
      <%= f.text_field :category %>
    </div>
    <div class='card'>
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<h1>Details of <%= @restaurant.name %></h1>
<p>Address: <%=@restaurant.address%></p>
<p>Phone nber: <%=@restaurant.phone_number%></p>
<p>Category: <%=@restaurant.category%></p>
<p><%= link_to "Add a review", new_restaurant_review_path(@restaurant) %></p>
<p><%= link_to "See all reviews", restaurant_reviews_path(@restaurant) %></p>
<p><%= link_to 'Delete the restaurant', restaurant_path(@restaurant), method: :delete %></li></p>
<p><%= link_to "Back to the list", restaurants_path %></p>

app/views/reviews/index.html.erb
<h1>Reviews of <%= @restaurant.name  %></h1>
<ul>
  <% @reviews.each do |review| %>
    <p><%=review.content%> (rating: <%=review.rating%>)</p>
  <% end %>
</ul>
<p><%= link_to "Back to the restaurant's details", restaurant_path(@restaurant) %></p>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>